name: EpicChatGames
version: '${version}'
main: gg.minecrush.reactions.Reactions
api-version: '1.20'
folia-supported: true
author: awel
description: Reactions plugin with everything you need in it

commands:
  chatgames:
    description: Main command for Reactions plugin